//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityDetail
    {
        public int ID { get; set; }
        public int PaymentActivityID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual PaymentActivity PaymentActivity { get; set; }
    }
}
