//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRequest
    {
        public int ID { get; set; }
        public int EmployeID { get; set; }
        public int CarID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
