//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyForm
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> CarID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> JobID { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual Job Job { get; set; }
    }
}
