//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRequest
    {
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public int RequesterID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual Product Product { get; set; }
    }
}
