//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.MVC.FieldContact.CustomFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> Delivered { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<int> ContQuantity { get; set; }
        public Nullable<double> SalePrice { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual Product Product { get; set; }
    }
}
