//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.MVC.FieldContact.CustomFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceForm
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> CompEmp1ID { get; set; }
        public Nullable<int> CompEmp2ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public string JobDescription { get; set; }
        public string ServiceDetails { get; set; }
        public string SerialNo { get; set; }
        public Nullable<bool> IsWarrantied { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<bool> IsArıza { get; set; }
        public Nullable<bool> IsBakım { get; set; }
        public Nullable<bool> IsSupervice { get; set; }
        public Nullable<bool> IsDevreyeAlma { get; set; }
        public Nullable<bool> IsEducate { get; set; }
        public Nullable<bool> IsMontage { get; set; }
        public Nullable<bool> IsDelivering { get; set; }
        public Nullable<bool> IsMeeting { get; set; }
        public Nullable<bool> IsFirsManint { get; set; }
        public Nullable<bool> IsSecondMaint { get; set; }
        public Nullable<bool> IsThirdMaint { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompEmployee CompEmployee { get; set; }
        public virtual CompEmployee CompEmployee1 { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
