//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.MVC.FieldContact.CustomFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserXAction
    {
        public int UserID { get; set; }
        public int ActionID { get; set; }
    
        public virtual Application_Action Application_Action { get; set; }
        public virtual Membership_User Membership_User { get; set; }
    }
}
